### ISSUE TITLE
Invisible special characters appended to sanity object strings

### ISSUE THREAD

**Issue by FancyJeff** [nuxt-modules/sanity#1007]
### Version
module: 1.8.3
nuxt: 3.11.2

### Nuxt configuration
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["@nuxtjs/sanity"],

  sanity: {
    projectId: process.env.NUXT_SANITY_PROJECT_ID,
    dataset: process.env.NUXT_SANITY_DATASET,
    useCdn: true, // `false` if you want to ensure fresh data
    apiVersion: process.env.NUXT_SANITY_API_VERSION || '2024-03-15',
    visualEditing: {
      studioUrl: process.env.NUXT_SANITY_STUDIO_URL || 'http://localhost:3333',
      token: process.env.NUXT_SANITY_API_READ_TOKEN,
      stega: true,
    },
  },
})

## Reproduction
Make a query to a text or string field in sanity.

**Link:** 
[ ] https://stackblitz.com/edit/nuxt-sanity
[x] GitHub repository
https://github.com/FancyJeff/test-sanity-nuxt

#### What is expected?
Getting a basic string

#### What is actually happening?
A huge number of special characters is being appended to the end of the string

## Additional information
This does not occur on package version 1.8.3, I tested it as early as 1.10.0 and it still was occurring.

I have created an empty package with no other packages and used the latest versions of everything and its still occurring.

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

### What is actually happening?
Screen shot of the chrome dev tools
![Screenshot 2024-05-27 123818](https://github.com/nuxt-modules/sanity/assets/30362360/625d8084-71e4-4dda-96c5-1702dbbd40c3)

**Comment by javangriff** [comment]
These special characters are added by Sanity when using visual editing mode.  They allow Sanity to work out where it needs to go withing Sanity studio when clicking on the content. You can read more about is [here](https://www.sanity.io/docs/stega).

If you need to remove these characters from the string you can import `stegaClean` from `@sanity/client/stega`.

**Comment by jesperbjerke** [comment]
I think there is a problem here though. It looks like the stega encoding is enabled all the time when using this module and having visual editing configured. But as far as I understand, stega and anything visual editing-related are only supposed to be enabled when preview mode is enabled? Tried to find more clear answers in the Sanity docs and they ever only mention stega in relation to preview mode. 
Sorry for pinging @danielroe

**Comment by Slgoetz** [comment]
Yea, if we could expose the sanityClient stega config, we would be able to turn it on/off globally

**Comment by rdunk** [comment]
Thanks @jesperbjerke, I think that assumption is correct. I've added a fix in #1023.

**Comment by notflip** [comment]
@rdunk This is still happening for me, even when the /preview/enable route has not been hit, and I'm not in preview mode.

**Comment by rdunk** [comment]
@notflip: `1.11.4` doesn't include the fix, but @danielroe has kindly released a new version (`1.11.5`) that does.

**Comment by notflip** [comment]
@rdunk I just saw it! Thanks a lot. Is the `stegaclean` method still needed for some cases then? I suppose only to clean the input when effectively using the preview mode?

**Comment by rdunk** [comment]
Yes exactly, it's still useful for all sorts of things, like str length comparisons.

Going to close this one now, thanks for the report. Please reopen if the issue persists.

**Comment by notflip** [comment]
@rdunk One more question, because I'm using a lot of comparisons in my Vue code (for example block.imagePosition, block.verticalAlign), what if I set `stega: false`, which features will not work then? Does this break the live editing?

**Comment by rdunk** [comment]
If you'd prefer not to use stega you can manually map content/create overlays using  `createDataAttribute` and `encodeDataAttribute`. Docs [here](https://www.sanity.io/docs/visual-editing-overlays#0fc0c885688b).

**Comment by notflip** [comment]
@rdunk Thanks for this, is there an example when using nuxt/sanity? For example the docs of `encodeDataAttribute` show

```
import { QueryResponseInitial, useQuery } from "@sanity/react-loader";
```

Do we have an example of how to use this with nuxt in general, or nuxt/sanity?

**Comment by notflip** [comment]
@rdunk Thanks for this, do you know the nuxt/sanity equivalent to `import { createDataAttribute } from "@sanity/visual-editing"`?

**Comment by rdunk** [comment]
@notflip Good point. I've added that as a separate issue and created a PR to add an auto-import for it.
