### ISSUE TITLE
SanityContent causing [Vue Warn] & console log flooding

### ISSUE THREAD

**Issue by m7d411** [nuxt-modules/sanity#1058]
## Description
The SanityContent component is causing the following Vue error:
`[Vue warn]: Extraneous non-props attributes (data-v-inspector) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.`
In addition to this, for larger blocks arrays, there is a significant issue where the console gets flooded with log messages, eventually preventing the local development environment from starting or responding properly.

### Version
```json
"@nuxtjs/sanity": "^1.12.1"
"nuxt": "^3.13.2"
"vue": "^3.5.6"
```

### Reproduction
[StackBlitz](https://stackblitz.com/edit/stackblitz-starters-jmhao3?file=app.vue)

### Steps to Reproduce
1.	Use a `<SanityContent />` with a blocks array.
2.	Start the local development server.
3.	Observe the console flooding with warnings or errors.

### Expected Behavior
No warnings about extraneous non-prop attributes should appear.

**Comment by hajiskyy** [comment]
had the same issue, its likely to be related to Vue 3.5. it seems like it requires components to set inherit attribute to false
