### ISSUE TITLE
Styling appears broken on @nuxtjs/sanity docs website

### ISSUE THREAD

**Issue by michaelreinhard1** [nuxt-modules/sanity#1069]
Hi, I wanted to report that the styling on the @nuxtjs/sanity docs website appears to be broken. The website is functional but the styling is not being applied correctly, making the content difficult to read.

https://sanity.nuxtjs.org/

Thanks in advance!

**Comment by danielroe** [comment]
thanks for flagging! should be resolved with a lockfile update + a hotfix in `pinceau`
