### ISSUE TITLE
Listen for 'loading' events in sanity fetch both globally and locally

### ISSUE THREAD

**Issue by toddpadwick** [nuxt-modules/sanity#520]
hey, Nuxt/Sanity team. I'm new to using this module. Having previously used Nuxt/Apollo which has an out-of-the-box loading listener, I am now unsure how to recreate the same logic to Nuxt/sanity. I would like to achieve the following:

- listen for `loading` of a single sanity fetch query, and display a loading icon in the same component accordingly.
- Listen for `loading` of all/any sanity fetch queries occurring in the app, and display a global loading icon in the layout component.

I am using _Nuxt 3.0.0-rc.11_ and _Nuxt/sanity ^1.3.0_

Whats the best practice way to handle these features?

**Comment by danielroe** [comment]
You can use the built-in `<NuxtLoadingIndicator>` component to show a global loading bar: https://v3.nuxtjs.org/api/components/nuxt-loading-indicator#nuxtloadingindicator

For within-component loading, you can access the `pending` property returned by `useSanityQuery`.

**Comment by danielroe** [comment]
I'm closing this issue as I think I've answered it, but do let me know if I can be of any more help.
