### ISSUE TITLE
sanity.nuxtjs.org/getting-started page in unavailable?

### ISSUE THREAD

**Issue by arb85** [nuxt-modules/sanity#535]
## Reproduction
Navigate to https://sanity.nuxtjs.org/getting-started/quick-start

**Link:** 
- [Sanity Nuxt Module](https://sanity.nuxtjs.org)

#### What is expected?
To view the documentation

#### What is actually happening?
Error 500 (screenshot below)

<img width="1033" alt="Screenshot 2022-10-25 at 09 53 11" src="https://user-images.githubusercontent.com/13294791/197716092-78fc14c2-da02-41c0-87cf-7c5ba7c9f526.png">

**Comment by arb85** [comment]
Thank You for the repository 😉
Let me know if I can help!

**Comment by davidstackio** [comment]
All I'm getting is a black screen:
![image](https://user-images.githubusercontent.com/2013388/199849156-41bb9f5b-15d1-427a-a06b-e901689c863e.png)

**Comment by arb85** [comment]
> All I'm getting is a black screen: 

Yes, also a black screen here:
I've checked the console:

<img width="1203" alt="Screenshot 2022-11-04 at 00 11 34" src="https://user-images.githubusercontent.com/13294791/199852460-786b6d1e-6b21-4f3e-8084-1cf5e5ae7e2d.png">

**Comment by danielroe** [comment]
Ugh... But thanks! ❤️

**Comment by brandonmlyon** [comment]
Same, it's not working for me. Is there an ETA when this will be fixed? If not then I might not be able to use the starter kit as I can't figure out how to get it started (and this is not my first Rodeo, I've used Next+Sanity before as well as Nuxt).

**Comment by danielroe** [comment]
Apologies. I've temporarily reverted to a working version, but will need to update the docs dependencies to resolve properly.

**Comment by pascalwengerter** [comment]
@danielroe has this been resolved? https://sanity.nuxtjs.org/getting-started/quick-start shows content, but not sure if it's the "old working version" you referred to in your most recent comment?

**Comment by danielroe** [comment]
Oh, yes this can be closed. It was resolved in https://github.com/nuxt-modules/sanity/pull/590.
