### ISSUE TITLE
useSanity() returns no result for query inside of an object using the "count()" function

### ISSUE THREAD

**Issue by bstnhnsl** [nuxt-modules/sanity#536]
### Version
module: 1.4.1
nuxt: 3.0.0-rc.11

## Reproduction
**Link:** 
[stackblitz ] (https://stackblitz.com/edit/nuxt-sanity-gb9fhj?file=app.vue)

#### What is expected?
`useSanity()` should return a list of movies regardless of being inside of an object

#### What is actually happening?
`useSanity()` doesn't return a list of movies
the exact same query works in the sanity studio when using vision

## Checklist
* [ X ]  I have tested with the latest Nuxt version and the issue still occurs
* [ X ]  I have tested with the latest module version and the issue still occurs
* [ X ]  I have searched the issue tracker and this issue hasn't been reported yet

### Steps to reproduce
1. Install sanity with movie dataset
2. install Nuxt 3 & sanity module
3. query for all movie documents that are referenced by a screening document using an object with an attribute key using useSanity() or useSanityQuery()

`{  'movies': *[_type == 'movie' && count(*[_type=='screening' && references(^._id)]) > 0] }`

**Comment by danielroe** [comment]
You need to update your `apiVersion`:

```ts
export default defineNuxtConfig({
  sanity: {
    apiVersion: 'v2021-10-21',
  }
})
```
