### ISSUE TITLE
[Question] How to implement preview-mode with Nuxt3

### ISSUE THREAD

**Issue by rylanharper** [nuxt-modules/sanity#548]
Hey there! Always appreciate the work that you put into this repo, it never goes unnoticed 🙏 

I am struggling with trying to implement [preview-mode](https://www.sanity.io/docs/preview-content-on-site) with Nuxt3 when using `nuxt-generate`. I have everything correctly set up on the Sanity studio end of things, but my site isn't updating when I move my preview route outside of `localhost` (ideally it will be the project domain or netlify/vercal domain).

The docs make reference to this [here](https://sanity.nuxtjs.org/getting-started/configuration#disablesmartcdn), but it seems that is a Nuxt2 feature... 

Any help would be really appreciated!

**Comment by jjjuulliiaann** [comment]
You are right about the Nuxt preview mode, it seems to be missing in Nuxt 3 (for now). 

You still can implement a preview mode yourself by listening to the url parameter (?preview=true) and loading the preview data with an additional client (with `useCdn: false, withCredentials: true`)

I am not sure about static nuxt-generate but I use it like this with universal rendering mode in my template [(link)](https://github.com/jjjuulliiaann/sanity-nuxt-3-starter#frontend).

**Comment by rylanharper** [comment]
Hey @jjjuulliiaann yeah I saw that on the repo you made. I'll go ahead and give that a try and see how that goes.. Have you implemented the preview mode like that for personal/client sites yet, and if so, does it work well?

**Comment by jjjuulliiaann** [comment]
Yes, I used it in a similar way before and it works well. What you have to keep in mind is building your groq queries in a way, that also works for unpublished pages as well as handling missing data in your nuxt pages/components.

**Comment by rylanharper** [comment]
Sounds good. Thanks for the help!
