### ISSUE TITLE
Composables (useSanity, etc.) are not found with Nuxt 3.0.0 (stable)

### ISSUE THREAD

**Issue by svnldwg** [nuxt-modules/sanity#563]
### Version
module: 1.4.1
nuxt: 3.0.0

## Reproduction

**Link:** 
https://stackblitz.com/edit/nuxt-sanity-vsw5qz?file=package.json

#### What is expected?
No errors
#### What is actually happening?
Gives errors, can not find the nuxtjs/sanity composables:

> [unimport] failed to find "useSanity" imported from "#imports"  

> [unimport] failed to find "createSanityClient" imported from "#imports" 

#### Steps to reproduce
Just click the link and start nuxt.

## Additional information
With nuxt 3.0.0-rc.13 it is working.

## Checklist
* [X]  I have tested with the latest Nuxt version and the issue still occurs
* [X]  I have tested with the latest module version and the issue still occurs
* [X]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by danielroe** [comment]
I think it's an old version of kit being included in your deps. Would you try with @nuxtjs/sanity@1.5.0?

**Comment by svnldwg** [comment]
I can confirm that this is fixed with @nuxtjs/sanity@1.5.0. Thank you, works fine now with Nuxt 3.0.0!
