### ISSUE TITLE
Please update module version on npm.

### ISSUE THREAD

**Issue by procrates** [nuxt-modules/sanity#646]
Node still installs v.1.5 when deploying to vercel.

Thanks!

**Comment by danielroe** [comment]
Have you tried updating your package json? The module is published to npm: https://www.npmjs.com/package/@nuxtjs/sanity

**Comment by procrates** [comment]
Strange it didnt update on npm on my end this morning. Might be a caching problem. IDK. I can see it now. Thanks"
