### ISSUE TITLE
Getting 500 trying to run Sanity + Nuxt 3 on Cloudflare Workers

### ISSUE THREAD

**Issue by VicFleur** [nuxt-modules/sanity#660]
### Version
module: 1.6.0
nuxt: 3.1.1

### Nuxt configuration
Super simple setup
```
sanity: {
    projectId: '########',
    minimal: true
}
```

using `minimal` or not doesn't have any effect, using `useSanityQuery` or `sanity.fetch` does not matter either

## Reproduction
Just create a barebones Nuxt 3 app, install Sanity and run a simple groq query through `useSanityQuery`

#### What is expected?
getting Sanity's content on the server side

#### What is actually happening?
it works only on the client side, while every time a query is fired from SSR it returns a 500 error with the following message:
`The 'credentials' field on 'RequestInitializerDict' is not implemented.`

I am aware that this might be mainly due to a feature not supported by Cloudflare as noted in [this thread](https://github.com/cloudflare/wrangler2/issues/2514). However, other libraries with a similar problem seem to have some sorts of way to bypass the thing if I'm not misinterpreting [these answers](https://github.com/sindresorhus/ky/issues/366).

So I was wondering if Sanity's module has a way around this missing bit or not.

**Comment by warflash** [comment]
Hey @VicFleur, out of curiousity, have you stumbled across a workaround for this?

**Comment by VicFleur** [comment]
@warflash no, we ended up self-hosting the app instead. Looks like the "solution" would be avoiding the `credentials` field entirely when fetching content, but the issue isn't resolved in the linked threads either, as it's probably due to a bug or something missing on Cloudflare

**Comment by warflash** [comment]
Appreciate the response!
Looking through the issues you linked the "fix" or rather workaround seems pretty straight foward actually. https://github.com/sindresorhus/ky/pull/559/files
@danielroe Do you think an approach like this would be fine for this module as well - or should this be fixed elsewhere instead?

**Comment by danielroe** [comment]
Interesting. I would certainly be up for hotfixing here but probably deserves to be in https://github.com/unjs/ofetch which we are using under the hood.

**Comment by danielroe** [comment]
Actually, I think we can just omit on the server. (Still should be raised upstream, but I think we have a local solution.)
