### ISSUE TITLE
Nuxt 3.4/3.5 runtime config changes might break module

### ISSUE THREAD

**Issue by davidstackio** [nuxt-modules/sanity#758]
### Version
module: 1.6.0
nuxt: 3.4.1

### Nuxt configuration
```typescript
{
  modules: [
    '@nuxtjs/sanity',
  ],
  sanity: {
    // module options
  }
}
```

## Reproduction
Set up the module as per the documentation.

#### What is expected?
There shouldn't be a warning. So the docs probably need to change, **but even after I updated my `nuxt.config.ts` file the issue is still happening**, so I'm wondering if this module needs to be updated somehow?

#### What is actually happening?
When using this module with Nuxt 3.4.1 it will error the following:

```
[nuxt] [runtimeConfig] You are trying to access a public runtime config value (sanity) directly from the top level. This currently works (for backward compatibility with Nuxt 2) but this compatibility layer will be removed in v3.5. Instead, you can update config['sanity'] to config.public['sanity'].
```

This is a deprecation in 3.4 that will be removed in 3.5 (https://github.com/nuxt/nuxt/pull/20082).

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

### Steps to reproduce
1. Set up the module as per the documentation and use Nuxt 3.4.x
2. Change your `nuxt.config.ts` to:
```typescript
runtimeConfig: {
    public: {
      sanity: {
        projectId: "x",
        apiVersion: "x",
      },
  },
},
```

### What is expected?
No warning. As of Nuxt 3.5 it will be expected to access config.public.

**Comment by danielroe** [comment]
Thanks for the heads-up! This was a false positive warning, but I've merged a fix that will hide it in future.
