### ISSUE TITLE
Console warning: …public runtime config value (`sanity`) directly from the top level…

### ISSUE THREAD

**Issue by lucpotage** [nuxt-modules/sanity#785]
### Version
module: 1.7.1
nuxt: 3.4.3

### Nuxt configuration
```
export default defineNuxtConfig({
  modules: [
    '@nuxtjs/sanity',
  ],
  sanity: {
    projectId: process.env.SANITY_PROJECT_ID,
    apiVersion: '2023-03-27'
  },
```

## Reproduction

I get the following warning in the browser console.

> [nuxt] [runtimeConfig] You are trying to access a public runtime config value (`sanity`) directly from the top level. This currently works (for backward compatibility with Nuxt 2) but this compatibility layer will be removed in v3.5. Instead, you can update `config['sanity']` to `config.public['sanity']`.

**Comment by danielroe** [comment]
You can safely ignore this; it is not an issue with this module.
