### ISSUE TITLE
Nuxt warning in the console about runtimeConfig?

### ISSUE THREAD

**Issue by yevhendevbox** [nuxt-modules/sanity#822]
Hi there, i'm try to learn this framework right now by creating simple portfolio web site. I'm using Sanity Studio as content management tool. Sims like every thing working just fine, but i have some warning in the console:

`[nuxt] [runtimeConfig] You are trying to access a public runtime config value (`sanity`) directly from the top level. This currently works (for backward compatibility with Nuxt 2) but this compatibility layer will be removed in v3.5. Instead, you can update `config['sanity']` to `config.public['sanity']`.`

My nuxt.config.ts file: 
```
export default defineNuxtConfig({
  modules: [
    '@nuxtjs/eslint-module',
    '@nuxt/devtools-edge',
    'nuxt-icon',
    '@nuxtjs/sanity',
  ],
  runtimeConfig: {
    public: {
      sanity: {
        projectId: '..........',
        dataset: 'production',
      },
    },
  },
```
Any tips how to fix it?

**Comment by danielroe** [comment]
You can update your Nuxt version to silence this warning. Don't worry, nothing is broken; it's a false positive.
