### ISSUE TITLE
Sanity "Perspective" update for Nuxt-Sanity

### ISSUE THREAD

**Issue by ASoldo** [nuxt-modules/sanity#836]
Sanity has published "Perspective" today. It is a fix for some workarounds that were present for some time.
Since I'm relatively new to sanity and still learning it, this will set us noobs on the correct path instead of doing this workarounds for no reason.

Mainly what we need is this "perspective" option in our config so we can use this feature without issues.

I know this is fresh and dropped today but just wanted to point out that this feature was missing in Sanity and now we have it BUT only for React so far. :D

Thank you for reading this request!

**Comment by Nelwhix** [comment]
@danielroe can you assign this to me, I would like to try and add the feature

**Comment by Nelwhix** [comment]
@ASoldo Can you send the link to Sanity's docs on perspective, can't find it there

**Comment by ASoldo** [comment]
yes, it's here: --> https://www.sanity.io/docs/perspectives

also this is announcement from slack:
```md
Introducing Perspectives, and upgrades to our preview tooling!
Are you familiar with this piece of GROQ?
!(_id in path('drafts.**'))
Some of you—strike that—many of you have asked us about how to filter in or out drafts for the last couple of years. And the answer has always been adding the above condition to all your GROQ queries or removing the authentication in the request to prevent drafts from coming through. It works, but it doesn’t feel elegant. Well, I’m very happy to tell you that those days are over because of something we call Perspectives.
Perspectives is a new foundational feature for Content Lake that lets you pull the right content for the right context using the same GROQ query. And the first perspectives we’re releasing for everyone lets you specify if you want:
the newest version of a document published or draft (previewDrafts)
only published docs, and no drafts whatsoever (published)
or the default behavior that you’re used to (raw)
The way you can use Perspectives depends on how you integrate with Sanity, but for most of you it’s probably going to be to update the JavaScript client and use its new configuration:
import {createClient} from '@sanity/client'

const client = createClient({
  ...config,
  useCdn: true,
  perspective: 'published',
})
Under the hood, what the client does is to add the URL parameter &perspective=published to the API request. You can also do this if you integrate directly with the API, or have your own tooling. We have also upgraded the Vision plugin to let you select available perspectives when experimenting with queries. Perspectives will still respect your permissions, meaning that you can’t get drafts with previewDrafts if the request isn’t authenticated. [Learn more about Perspectives in our documentation](https://www.sanity.io/docs/perspectives?utm_source=community&utm_medium=organic_social&utm_campaign=summer-release-demo&utm_content=community-announcement).
```

**Comment by Nelwhix** [comment]
@danielroe  the PR is [here](https://github.com/nuxt-modules/sanity/pull/837). can you suggest some test cases I should add

**Comment by ASoldo** [comment]
hi @Nelwhix, is there any update regarding this PR? Thank you!

**Comment by Nelwhix** [comment]
> hi @Nelwhix, is there any update regarding this PR? Thank you!

I am waiting for @danielroe to review and merge

**Comment by Nelwhix** [comment]
@ASoldo a new release(v1.8.0) has been made to add the perspective option. I believe usage should look like this: 
![sanity changes](https://github.com/nuxt-modules/sanity/assets/58360242/4a4394b4-4f26-4968-9d1e-4d5fd4308094)

**Comment by ASoldo** [comment]
Awesome! Thank you so much for taking time to make this update.

**Comment by Eric-llos** [comment]
Should this perspective option appear in @nuxtjs/sanity documentation? I had no idea about this option existed 👍

**Comment by danielroe** [comment]
It should!
