### ISSUE TITLE
'listen' does not exist

### ISSUE THREAD

**Issue by mayoforkovic** [nuxt-modules/sanity#870]
### Version
module: 1.8.0
nuxt: 3.6.5

#### What is expected?
Client library is not complete? 
In [docs there is](https://sanity.nuxtjs.org/getting-started/usage#client) listen method referenced on client object but its not included in library.

## Reproduction
```
const sanity = useSanity()
onMounted(() => {
  console.log(sanity.client)
  console.log(sanity.client.listen) // Property 'listen' does not exist on type '{ clone: () => any; fetch (query: string, params?: Record  | undefined): Promise ; }'
})
```

**Comment by danielroe** [comment]
This method is only available if not using the minimal client (which is enabled by default).

**Comment by mayoforkovic** [comment]
I see now, Thanks!
