### ISSUE TITLE
Perspectives for Content Lake

### ISSUE THREAD

**Issue by LucaArgentieri** [nuxt-modules/sanity#880]
### Is your feature request related to a problem? Please describe.

I'm used to adding ```&& !(_id in path("drafts.**"))``` at the end of my groq query to get only published elements.

### Describe the solution you'd like to see
Sanity recently added a new feature called perspectives, where you can filter substantially by 'raw', 'previewDrafts' and 'published'
And you can use it in the client like this:
```
import {createClient} from '@sanity/client'

const client = createClient({
  ...config,
  perspective: 'published', // 'raw' | 'previewDrafts' | 'published'
})
```

Should be great have this feature in nuxt sanity!
Link to the doc: https://www.sanity.io/docs/perspectives

**Comment by danielroe** [comment]
Believe it or not, this is supported as of v1.8.0: https://github.com/nuxt-modules/sanity/pull/837!
