### ISSUE TITLE
useSanity in server handler broken in build version (module not found)

### ISSUE THREAD

**Issue by thijs-justacodename** [nuxt-modules/sanity#891]
### Version
module: 1.8.0 / 1.8.1
nuxt: 3.6.5

(under the hood, this issue starts occurring since @sanity/client v6.4.1)

[nuxt] [request error] [unhandled] [500] Cannot find module '/somepath/nuxt-website/.output/server/node_modules/@sanity/client/dist/index.cjs.js' imported from /somepath/nuxt-website/.output/server/chunks/_queryName_.mjs
  at new NodeError (node:internal/errors:399:5)  
  at finalizeResolution (node:internal/modules/esm/resolve:326:11)  
  at moduleResolve (node:internal/modules/esm/resolve:945:10)  
  at defaultResolve (node:internal/modules/esm/resolve:1153:11)  
  at nextResolve (node:internal/modules/esm/loader:163:28)  
  at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)  
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)  
  at link (node:internal/modules/esm/module_job:76:36)

This issue does NOT exist if we explicitly add another `@sanity/client` dependency to `6.4.0`. The issue occurs if we do not explicitly have a `@sanity/client` dependency, AND the issue DOES occur if we have an explicit dependency on `@sanity/client` v6.4.1 or up. It seems that [`@sanity/client` 6.4.1](https://github.com/sanity-io/client/compare/v6.4.0...v6.4.1) changed their exports and Nuxt is unable to pick those up?

## Reproduction

Explanation:
- We use a composable that "proxies" queries to Sanity CDN, without exposing the query contents. We have a server handler (in server/api/[queryName].ts which performs a sanity.fetch. 
- The only dependency we have defined explicitly is @nuxtjs/sanity
- Running `yarn dev` works fine. 
- Running `yarn build && yarn preview` exposes the above issue.

1. Create a server handler in server/api/something.ts
2. Define an eventHandler or cachedEventHandler
3. In that eventHandler, use the composable `useSanity()`
4. Run `yarn build && yarn preview`
5. Perform a request to the server endpoint at /api/something

```
// something.ts
export default defineEventHandler(async () => {
  const sanity = useSanity();
  const response = await sanity.fetch(query, params).catch((err) => {
    throw createError({
      statusCode: err.statusCode,
      statusMessage: err.message,
      cause: err,
    });
  });

  return response;
})

```

#### What is expected?
1. That `useSanity()` is able to use the built-in client if it is not explicitly made a dependency
2. That using `useSanity()` does not cause 500 errors with module not found errors

#### What is actually happening?
Module not found errors in Nuxt build version, but not in dev.
`@sanity/client` changed their exports in 6.4.1, this breaks `@nuxtjs/sanity` for `useSanity()` in server event handlers.

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by rylanharper** [comment]
Wow this could be what is breaking my build. Maddening lol 😵‍💫

**Comment by danielroe** [comment]
For not, try pinning to a lower version of sanity/client in your project.

**Comment by rylanharper** [comment]
@danielroe just tested this on Netlify/Vercel by adding `@sanity/client: 6.4.0` as @thijs-justacodename mentioned.. Sites are all working now!

**Comment by CalebKester** [comment]
Thank you for this! I upgraded my dev project 2 weeks ago and the deployments broke and just getting around to looking into it. The solution of `pnpm i @sanity/client@6.4.0` works for me!

**Comment by thunder87** [comment]
Getting exactly the same issue and I can confirm that explicitly setting `@sanity/client@6.4.0` fixed the 500 error on Vercel. 🥳

`[nuxt] [request error] [unhandled] [500] Cannot find module '/var/task/node_modules/@sanity/client/dist/index.cjs.js' imported from /var/task/chunks/app/server.mjs
  at new NodeError (node:internal/errors:405:5)  
  at finalizeResolution (node:internal/modules/esm/resolve:329:11)  
  at moduleResolve (node:internal/modules/esm/resolve:992:10)  
  at moduleResolveWithNodePath (node:internal/modules/esm/resolve:936:12)  
  at defaultResolve (node:internal/modules/esm/resolve:1178:79)  
  at nextResolve (node:internal/modules/esm/loader:163:28)  
  at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)  
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)  
  at link (node:internal/modules/esm/module_job:76:36)`

**Comment by thijs-justacodename** [comment]
If you don't have an explicit dependency to `@sanity/client` but you use for example `@sanity/types` (which has a dependency on `@sanity/client`), you can also add this to your package.json:

```
"resolutions": {
  "@sanity/client@npm:^6.4.9": "6.4.0"
}
```

**Comment by danielroe** [comment]
Yes, it should be good now 👍
