### ISSUE TITLE
useSanityQuery return data: null

### ISSUE THREAD

**Issue by F-l-e-m** [nuxt-modules/sanity#903]
I call useSanityQuery() in the component, but from the server side, after reloading the page, this function returns **data: null** to me, why?
From the client side everything is ok

Code:
```

export const useSanityApi = async<Response>(query: string): NuxtTypeReturnUseApi<Response> => {
	const sanity = useSanity()
	const { data, error, status } = await useSanityQuery(query)
	console.log('data', data)//  <-- here data.value null

	return {
		data: data.value as Response,
		error,
		status
	}
}

```

**Comment by notflip** [comment]
@F-l-e-m What's the solution to this? I'm also having this issue.

**Comment by gsqrt2** [comment]
This issue should be reopened, this behavior is still standard.
