### ISSUE TITLE
Direct support for Visual Editing in Presentation

### ISSUE THREAD

**Issue by danielroe** [nuxt-modules/sanity#934]
https://www.sanity.io/docs/visual-editing

https://www.sanity.io/blog/introducing-presentation

**Comment by g0shed** [comment]
@danielroe any update on this? or not currently being worked on?

**Comment by danielroe** [comment]
See the linked pr. it's ready to go from my point of view, just waiting for a final review

**Comment by rdunk** [comment]
Just for some transparency: The delay is on my/our (i.e. Sanity's) end.

We are working on some general improvements to visual editing for to allow for easier and more incremental adoption. We may ship an opinionated Vue specific visual editing component which could _potentially_ provide some more OOTB Vue support outside of a Nuxt context, but could also be consumed by this module. We have some other items in review (as I write this) which may inform that work. The Nuxt implementation differs most from the other frameworks we are supporting, so we want to get this right and ship with an equal feature set.

Understand users have been waiting very patiently for this. It is being worked on as a priority, today.

**Comment by sebbean** [comment]
i'm also hoping for it ^_^

**Comment by danielroe** [comment]
This is implemented in the latest released version - do raise an issue if you have any problems...
