### ISSUE TITLE
import `client` from `@sanity-typed/client` instead of `@sanity/client`

### ISSUE THREAD

**Issue by xuzuodong** [nuxt-modules/sanity#959]
[`@sanity-typed`](https://github.com/saiichihashimoto/sanity-typed/tree/main) is a project completes Sanity's developer experience with typescript, which includes [`@sanity-typed/client`](https://github.com/saiichihashimoto/sanity-typed/tree/main/packages/client) with typed GROQ Results. It seems to be good if `nuxt-sanity` can optionally import client from this package. Is it possible to do so for better TypeScript DX?

**Comment by danielroe** [comment]
This is extremely cool. Would it be sufficient to allow the import to be configurable? Is it otherwise equivalent in API?

**Comment by xuzuodong** [comment]
I think the most intuitive way to do so is to add `typedClient` configuration in `sanity` field in `nuxt.config.ts`: 

```ts
sanity: {
    projectId: 'myProject',
    typedClient: true // requires users to explicitly set
},
```

Although this may be conflict with another configuration `minimal`, so maybe we can mix the two features up and do something like: 

```ts
sanity: {
    projectId: 'myProject',
    clientType: 'typed' // can also be 'minimal' or 'default', defaults to 'default'
},
```

**Comment by xuzuodong** [comment]
For those who want better TypeScript DX, Sanity now introduces an experimental feature called [Sanity TypeGen](https://github.com/sanity-io/sanity/releases/tag/v3.36.0) which supersedes [@sanity-typed](https://github.com/saiichihashimoto/sanity-typed/tree/main?rgh-link-date=2024-02-11T13%3A07%3A53Z). `Sanity TypeGen` supports generate types via its CLI, so I think this issue can be closed now.
