### ISSUE TITLE
NuxtLink not working when using useSanityQuery

### ISSUE THREAD

**Issue by LKosters** [nuxt-modules/sanity#969]
### Version
module: 1.9.0
nuxt: 3.10.3

#### What is expected?
If you click on a NuxtLink it changes to the page in the NuxtLink.

#### What is actually happening?
The URL changes but it does not change the page, this happens if useSanityQuery is used.

#### Steps to reproduce
Clone nuxt sanity repo with the movie example

## Additional information
NuxtLink does work if I query the data with useSanity but than the live preview does not work.

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by rdunk** [comment]
Thanks for reporting, I can replicate. Looks like there's a promise somewhere that never resolves, will hopefully have a fix for you shortly.
