### ISSUE TITLE
Parent operator provides wrong value (exact same code works in Vision)

### ISSUE THREAD

**Issue by notflip** [nuxt-modules/sanity#972]
### Version
```
  "dependencies": {
    "@nuxtjs/sanity": "^1.9.0",
    "@sanity/image-url": "^1.0.2",
    "@sanity/types": "^3.32.0",
    "nuxt": "^3.10.3",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
```

### Nuxt configuration
Default config, only projectId is passed
-->

## Reproduction
https://stackblitz.com/edit/nuxt-sanity-k5pc6u?file=app.vue

#### What is expected?
`^.title` should show the title as the alt tag for the image, now it shows nothing. This is however working fine in Vision, see image below

This is the structure code (from Sanity)
```
  "gallery": {
    "_type": "gallery",
    "images": [
      {
        "_key": "cdc2286fac70",
        "_type": "image",
        "asset": {
          "_ref": "image-78876fa734dd74bf790054edb5f6f6c166acb0fe-8767x6267-jpg",
          "_type": "reference"
        }
      }
    ]
  },
```

![Screenshot 2024-03-15 at 19 22 02](https://github.com/nuxt-modules/sanity/assets/4146384/67aaa01b-8433-4c5b-9ddd-562d666328be)

## Checklist
* [ x]  I have tested with the latest Nuxt version and the issue still occurs
* [ x]  I have tested with the latest module version and the issue still occurs
* [x ]  I have searched the issue tracker and this issue hasn't been reported yet

### Steps to reproduce
See stackblitz

**Comment by danielroe** [comment]
You should set your `apiVersion` in nuxt.config. It's currently on `1` for backwards compatibility.

**Comment by notflip** [comment]
@danielroe So you mean I have to set `apiVersion: '1'` in my nuxt.config.ts?

**Comment by danielroe** [comment]
No, set it to a newer version.

**Comment by notflip** [comment]
Ah right I see, thanks @danielroe !
