### ISSUE TITLE
Component inside <ClientOnly> is not rendered

### ISSUE THREAD

**Issue by huynhtehoa** [nuxt-modules/sanity#980]
Hi, first of all, thank you for the great module.

I'm new to both Nuxt and Sanity so I'm unsure if this is a bug or I am doing something wrong as I cannot find any documentation as well as related reports for this issue.

## Problem
I am facing a problem where component inside `<ClientOnly>` tag (or `cmp.client.vue`) is not rendered at all when using Sanity query.

<img width="1264" alt="image" src="https://github.com/nuxt-modules/sanity/assets/50204553/3d26f8b7-1c6f-496f-948e-737ffc4952a9">

The error message from the console is:
<img width="929" alt="image" src="https://github.com/nuxt-modules/sanity/assets/50204553/61f832f2-4ff9-41c6-a9f9-c29b6209c08f">

If I remove any of the Sanity composables (`useSanityQuery` or `useLazySanityQuery`), the client component will be rendered normally

## Workaround
A workaround (or intended feature) I found is to enable `minimal: true` for Sanity inside `nuxt.config.ts`

## Reproduction
You can clone these apps to test. But they are entirely fresh so any inited apps will do.
1. Nuxt: https://github.com/huynhtehoa/sanity-nuxt-test
2. Sanity: https://github.com/huynhtehoa/test-sanity

Note:
I tried to reproduce on StackBlitz [here](https://stackblitz.com/edit/nuxt-starter-dsckga?file=app.vue) but the issue does not occur. The only difference is I'm using `pnpm` for local development whereas StackBlitz uses `npm` (and its other env)

## System
- OS: WSL 2 Ubuntu 20.04
- Node: 18.20.0
- pnpm: 8.15.5
- Nuxt: 3.11.1
- @nuxtjs/sanity: 1.10.1

**Comment by felix-dolderer** [comment]
@huynhtehoa Can you check if the issue still comes up for you?

I tried reproducing the issue by initializing a new nuxt project and a new sanity project.
Data loads and component is shown as expected and I even tried various scenarios for using `useSanityQuery` that I experienced may lead to different behaviour for other issues.

- [x] `useSanityQuery` in `app.vue` with a plain `<ClientOnly>` component (your setup on stackblitz)
- [x] `useSanityQuery` in the `<ClientOnly>` component, and having the component, directly in `app.vue`
- [x] `useSanityQuery` in a pages-route with a plain `<ClientOnly>` component directly calling the page
- [x] `useSanityQuery` in a pages-route with a plain `<ClientOnly>` component, using client-side navigation to open the page
- [x] `useSanityQuery` in the `<ClientOnly>` component itself, and having the component in a pages-route, directly calling the page
- [x] `useSanityQuery` in the `<ClientOnly>` component itself, and having the component in a pages-route, using client-side navigation to open the page

All of them worked locally as well as on stackblitz.
